import { View, Text, ScrollView, Image, Alert } from "react-native";
import React, { useCallback, useState } from "react";
import { useFocusEffect } from "@react-navigation/native";
import { SafeAreaView } from "react-native-safe-area-context";
import { StatusBar } from "expo-status-bar";
import { useDispatch, useSelector } from "react-redux";
import FormField from "../../components/FormField";
import CustomButton from "../../components/CustomButton";
import { icons } from "../../constants";
import { router, useLocalSearchParams } from "expo-router";
import { updateProfile } from "../../lib/redux/actions/userActions";
import { resetUserState } from "../../lib/redux/slices/users";
import Message from "../../components/Message";

const ResetPassword = () => {
  const dispatch = useDispatch();
  const { loading, updateSuccess, error } = useSelector((state) => state.user);
  const { password } = useLocalSearchParams();
  const [form, setForm] = useState({
    newPassword: "",
    confirmPassword: "",
  });
  const [successMsg, setSuccessMsg] = useState(null);
  const [updating, setUpdating] = useState(null);

  const submit = () => {
    if (!form.newPassword || !form.confirmPassword) {
      Alert.alert("Error", "All fields required!");
      return;
    }
    dispatch(updateProfile({ ...form, oldPassword: password }, "password"));
  };

  useFocusEffect(
    useCallback(() => {
      if (updateSuccess) {
        setSuccessMsg(
          "Password reset successfully! Please wait as you're redirected..."
        );
        const interval = setInterval(() => {
          dispatch(resetUserState());
          router.push("/userhome");
        }, 3000);

        return () => clearInterval(interval);
      }
        setUpdating(loading);
    }, [dispatch, router, updateSuccess, loading])
  );

  return (
    <SafeAreaView className='h-full bg-secondary px-4 flex-row justify-center items-center'>
      <ScrollView className=''>
        <View className='bg-white p-4 rounded-lg'>
          <Text className='text-orange font-psemibold text-3xl text-center mt-4 mb-1'>
            Reset Password
          </Text>
          {successMsg ? (
            <Message
              description={successMsg}
              icon={icons.checkMark}
              variantStyles='bg-green-100 space-x-2'
              descriptionStyles='text-green-500'
            />
          ) : error ? (
            <Message description={error} icon={icons.warning} />
          ) : (
            <Message
              description=' Your current password was autogenerated. Please reset it for
                additional security.'
              icon={icons.warning}
            />
          )}
          <FormField
            title='New Password'
            placeholder='Enter new password...'
            value={form.newPassword}
            handleChangeText={(e) => setForm({ ...form, newPassword: e })}
            otherStyles='mb-2'
            type='password'
          />
          <FormField
            title='Confirm New Password'
            placeholder='Enter new password again...'
            value={form.confirmPassword}
            handleChangeText={(e) => setForm({ ...form, confirmPassword: e })}
            otherStyles='mb-2'
            type='password'
          />
          <CustomButton
            title='Submit'
            handlePress={submit}
            containerStyles='mt-3 w-full rounded'
            textStyles='text-white-100 text-xl text-white'
            isLoading={loading}
          />
        </View>
      </ScrollView>
      <StatusBar backgroundColor='#2A7353' style='light' />
    </SafeAreaView>
  );
};

export default ResetPassword;
